version: '3.4'

services:
  candidates_profiles:
    image: candidates_profiles
    depends_on:
      - db
      - cache
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

    env_file:
      - .env

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  cache:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local


